sms/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from sms import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('change-password/', views.PasswordChange.as_view(), name='change-password'),
    path('student_list/', views.StudentList.as_view(), name='studentList'),
    path('student_create/', views.StudentCreate.as_view(), name='studentCreate'),
    path('<int:pk>/course_details/', views.DepartmentCoursesDetail.as_view(), name='departmentCoursesDetail'),
    path('course_list/', views.CourseList.as_view(), name='courseList'),
]

studentmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms.urls')),
]

sms/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_define_id = models.CharField(unique=True, max_length=20, verbose_name="User ID")

    STUDENT = 'student'
    TEACHER = 'teacher'

    USER_TYPE = (
        (STUDENT, 'Student'),
        (TEACHER, 'Teacher'),
    )
    user_type = models.CharField(max_length=10, choices=USER_TYPE, default=STUDENT)

    GENDER_TYPE = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    gender = models.CharField(max_length=10, choices=GENDER_TYPE, default=GENDER_TYPE[0][0])
    dob = models.DateField(blank=True, null=True)
    address = models.TextField(verbose_name="Residence Address")
    contact_no = models.IntegerField()

    def __str__(self):
        return self.user.username


class Department(models.Model):
    name = models.CharField(max_length=256)
    code = models.CharField(max_length=10)
    description = models.TextField()
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by', on_delete=models.SET_NULL,
                                   null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Subject(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    code = models.CharField(max_length=10)
    credit = models.FloatField(default=0)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by', on_delete=models.SET_NULL, null=True,
                                   blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TeacherSubjectMapper(models.Model):
    teacher = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    subject = models.ManyToManyField(Subject)
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by', on_delete=models.SET_NULL, null=True,
                                   blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.teacher.user.username


class StudentDepartmentMapper(models.Model):
    student = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by', on_delete=models.SET_NULL, null=True,
                                   blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student.user.username

sms/forms.py
from django.contrib.auth.models import User
from django.forms import forms, ModelForm, CharField, EmailField, ModelChoiceField
from bootstrap_datepicker_plus.widgets import DatePickerInput

from sms.models import UserProfile, Department


class UserProfileForm(ModelForm):
    first_name = CharField(max_length=30)
    last_name = CharField(max_length=30)
    email = EmailField(max_length=254)
    department = ModelChoiceField(queryset=Department.objects.all())

    class Meta:
        model = UserProfile
        fields = ['user_define_id', 'gender', 'address', 'contact_no', 'first_name', 'last_name', 'email', 'department']

    def clean(self):
        super(UserProfileForm, self).clean()
        if User.objects.filter(username=self.cleaned_data['user_define_id']).exists():
            self._errors['user_define_id'] = self.error_class(['Already Registered.'])
        return self.cleaned_data

sms/views.py
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import transaction
from django.urls import reverse
from django.utils import timezone
from django.views.generic import TemplateView, CreateView, DetailView
from django_tables2 import SingleTableView

from sms.forms import UserProfileForm
from sms.models import StudentDepartmentMapper, UserProfile, Department, Subject
from sms.tables import StudentDepartmentTable, SubjectTable


class Login(views.LoginView):
    template_name = 'sms/login.html'
    first_time_login = False

    def form_valid(self, form):
        user = form.get_user()
        self.first_time_login = user.last_login
        return super(Login, self).form_valid(form)

    def get_success_url(self):
        try:
            date_difference = timezone.now() - self.first_time_login
        except:
            date_difference = timezone.now() - timezone.now()
        if not self.first_time_login or date_difference.days >= 30:
            return reverse('change-password')
        else:
            if self.request.user.userprofile.user_type == self.request.user.userprofile.STUDENT:
                return reverse('courseList')
            else:
                return reverse('studentList')


class PasswordChange(views.PasswordChangeView):
    template_name = 'sms/password_change.html'

    def get_success_url(self):
        if self.request.user.userprofile.user_type == self.request.user.userprofile.STUDENT:
            return reverse('courseList')
        else:
            return reverse('studentList')


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'sms/home.html'


class StudentList(LoginRequiredMixin, SingleTableView):
    model = StudentDepartmentMapper
    table_class = StudentDepartmentTable
    template_name = 'sms/student_list.html'

    def get_queryset(self):
        query = super(StudentList, self).get_queryset()
        # if not self.request.user.is_superuser:
        #     query = query.filter(
        #         siteauthsetting__in=model_site.SiteAuthSetting.objects.filter(user=self.request.user))
        return query


class StudentCreate(LoginRequiredMixin, CreateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'sms/create_student.html'

    @transaction.atomic()
    def form_valid(self, form):
        if form.is_valid():
            user: User = User.objects.create_user(username=form.cleaned_data['user_define_id'], password='Chembond@123',
                                                  first_name=form.cleaned_data['first_name'],
                                                  last_name=form.cleaned_data['last_name'])
            user.set_password(user.last_name)
            user.save()
            form.instance.user = user
            form.instance.user_type = UserProfile.STUDENT
            self.object = form.save()
            StudentDepartmentMapper.objects.create(student=self.object, department=form.cleaned_data['department'],
                                                   created_by=self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('studentList')


class DepartmentCoursesDetail(LoginRequiredMixin, DetailView):
    model = Department
    template_name = 'sms/department_course_detail.html'


class CourseList(LoginRequiredMixin, SingleTableView):
    model = Subject
    table_class = SubjectTable
    template_name = 'sms/course_list.html'

    def get_queryset(self):
        query = super(CourseList, self).get_queryset()
        if not self.request.user.is_superuser:
            query = query.filter(department=self.request.user.userprofile.studentdepartmentmapper.department)
        return query

sms/templates/sms/course_list.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Your Course List
                            <div class="float-end">
                                <a href="{% url 'departmentCoursesDetail' request.user.userprofile.studentdepartmentmapper.department.id %}"
                                   class="btn btn-primary">View Details</a>
                            </div>
                        </h5>
                        {% render_table table %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sms/templates/sms/create_student.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block custom-plugins-styles %}
    {{ form.media.css }}
    {{ doc_formset.media.css }}
    {{ files.media.css }}
{% endblock %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Student Create</h5>
                        <form method="post">
                            {% csrf_token %}
                            <div class="row mb-3">{{ form.user_define_id | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.department | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.first_name | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.last_name | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.email | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.gender | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.address | as_crispy_field }}</div>
                            <div class="row mb-3">{{ form.contact_no | as_crispy_field }}</div>
                            <button type="submit" class="btn btn-success" value="Submit">
                                <span class="oi oi-check"></span>
                                Save
                            </button>
                            <a type="submit" class="btn btn-secondary"
                               href="{{ request.META.HTTP_REFERER }}">
                                <span class="oi oi-x"></span>
                                Cancel
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block custom-plugins-js %}
    {{ form.media.js }}
{% endblock %}

sms/templates/sms/department_course_detail.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <nav>
                    <ol class="breadcrumb">
                        {% if request.user.userprofile.user_type == 'teacher' or request.user.is_superuser %}
                            <li class="breadcrumb-item"><a href="{% url 'studentList' %}">Student List</a></li>
                        {% else %}
                            <li class="breadcrumb-item"><a href="{% url 'courseList' %}">Course List</a></li>
                        {% endif %}
                        <li class="breadcrumb-item active">Course Details</li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Department Details</h5>
                        <p><b>Department Name: {{ object.name }} ({{ object.code }})</b></p>
                        <p>{{ object.description }}</p>
                    </div>
                </div>
                {% for course in department.subject_set.all %}
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.name }} ({{ course.code }})</h5>
                            <p><b>Course Credit: {{ course.credit }}</b></p>
                            <p>{{ course.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

sms/templates/sms/home.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Home</h5>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sms/templates/sms/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                                    <p class="text-center small">Enter your username & password to login</p>
                                    {% if form.non_field_errors %}
                                        <div class="alert alert-block alert-danger">
                                            <ul class='m-0'>
                                                {% for error in form.non_field_errors %}
                                                    <li>{{ error }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                </div>
                                <form class="row g-3 needs-validation" method="post" action="{% url 'login' %}">
                                    {% csrf_token %}
                                    <div class="col-12">
                                        <label for="id_username" class="form-label">Username</label>
                                        <div class="input-group has-validation">
                                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                                            <input type="text" name="username" class="form-control" id="id_username"
                                                   required>
                                            <div class="invalid-feedback">Please enter your username.</div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <label for="id_password" class="form-label">Password</label>
                                        <input type="password" name="password" class="form-control" id="id_password"
                                               required>
                                        <div class="invalid-feedback">Please enter your password!</div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit" value="login">Login
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

sms/templates/sms/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="container">
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-md-6 d-flex flex-column align-items-center justify-content-center">
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Reset Your Password</h5>
                                    {% if form.non_field_errors %}
                                        <div class="alert alert-block alert-danger">
                                            <ul class='m-0'>
                                                {% for error in form.non_field_errors %}
                                                    <li>{{ error }}</li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    {% endif %}
                                </div>
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="col-12">
                                        {{ form | crispy }}
                                    </div>
                                    <div class="col-12 mt-5">
                                        <button class="btn btn-primary w-100" type="submit" value="login">Reset
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

sms/templates/sms/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Sign Up
                        </h5>
                        {% crispy form %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sms/templates/sms/student_list.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Student List
                            <div class="float-end">
                                <a href="{% url 'studentCreate' %}" class="btn btn-primary">+ Add Student</a>
                            </div>
                        </h5>
                        {% render_table table %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sms/templates/sms/table/action_columns/student_actions.html
<a href="{% url 'departmentCoursesDetail' pk=record.department.id %}">See Courses</a>

sms/templates/sms/user_list.html
{% extends 'base.html' %}
{% load django_tables2 %}
{% block content %}
    <section class="section">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">User List</h5>
                        {% render_table table %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Student Teacher Portal</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'common/assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'common/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'common/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'common/assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'common/assets/css/style.css' %}" rel="stylesheet">
    {% block custom-plugins-styles %}
    {% endblock %}
</head>

<body class="toggle-sidebar">
<main id="main" class="main">
    {% include 'header.html' %}
    {% block content %}

    {% endblock %}
</main>
{% block custom-plugins-js %}
{% endblock %}
<!-- Vendor JS Files -->
<script src="{% static 'common/assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'common/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'common/assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'common/assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'common/assets/vendor/quill/quill.min.js' %}"></script>
<script src="{% static 'common/assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'common/assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'common/assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'common/assets/js/main.js' %}"></script>

</body>

</html>

templates/header.html
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="align-items-center justify-content-between text-center">
        {% if request.user.userprofile.user_type == 'student' %}
            <a href="{% url 'courseList' %}" class="logo align-items-center justify-content-between">
                <img src="assets/img/logo.png" alt="">
                <span>Student Management System</span>
            </a>
        {% else %}
            <a href="{% url 'studentList' %}" class="logo align-items-center justify-content-between">
                <img src="assets/img/logo.png" alt="">
                <span>Student Management System</span>
            </a>
        {% endif %}

    </div><!-- End Logo -->
    {% if request.user.is_authenticated %}
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{ request.user.get_full_name }}</span>
                    </a><!-- End Profile Iamge Icon -->
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{ request.user.get_full_name }}</h6>
                            <span>{{ request.user.userprofile.get_user_type_display }}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        {% if request.user.userprofile.user_type == 'teacher' or request.user.is_superuser %}
                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="{% url 'studentList' %}">
                                    <i class="bi bi-person"></i>
                                    <span>Student List</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if request.user.userprofile.user_type == 'student' or request.user.is_superuser %}
                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="{% url 'courseList' %}">
                                    <i class="bi bi-person"></i>
                                    <span>Course List</span>
                                </a>
                            </li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>
                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->
            </ul>
        </nav><!-- End Icons Navigation -->
    {% endif %}
</header><!-- End Header -->